### PR TITLE
Issue #20 Integrate glide

### PR DESCRIPTION
**Pull request by ty2**
#20

### CODE REVIEW

**Comment by troian** [comment]
@ty2 I saw you're PR. Reason I didn't merge huge changes I'm about to post. Current code base does not fit some of requirements thus need to be changed. Once I push we can update and merge.

**Comment by ipfans** [comment]
I suggest merge to [dep](https://github.com/golang/dep) to management for dependencies.

**Comment by troian** [comment]
@ipfans Thought to use it since it was beta. Now they conform it is safe for production so worth to try. Thanks

**Comment by troian** [comment]
Closed in favor to PR #44

**Pull request closed without merging**
